version: 2.1
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 5
  test:
    docker:
      - image: cimg/ruby:3.0.2
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 5
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
